# Generated by Django 5.0.2 on 2026-03-15 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=100)),
                ('image_path', models.ImageField(upload_to='shipping_images/')),
                ('captured_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='returnimage',
            name='image_hash',
        ),
        migrations.RemoveField(
            model_name='returnimage',
            name='manipulation_score',
        ),
        migrations.RemoveField(
            model_name='returnimage',
            name='metadata_flags',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='anomaly_score',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='fraud_probability',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='image_authenticity_score',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='ml_analysis',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='risk_factors',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='risk_score',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnimage',
            name='image',
            field=models.ImageField(upload_to='customer_uploads/'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_returns', models.IntegerField(default=0)),
                ('return_ratio', models.FloatField(default=0.0)),
                ('previous_rejections', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MLAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('similarity_prediction', models.CharField(blank=True, max_length=100, null=True)),
                ('damage_level', models.CharField(blank=True, max_length=50, null=True)),
                ('damage_probability', models.FloatField(blank=True, null=True)),
                ('customer_risk_score', models.FloatField(blank=True, null=True)),
                ('model_used', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ml_analysis', to='app.returnrequest')),
            ],
        ),
    ]
