# Generated by Django 5.0.2 on 2026-04-11 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shippingimages_remove_returnimage_image_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('manager', 'Return Manager'), ('delivery', 'Delivery Boy')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('picked', 'Picked'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pickup_image', models.ImageField(blank=True, null=True, upload_to='pickup_images/')),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_delivery_boy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL)),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='app.returnrequest')),
            ],
        ),
    ]
